name: lukodconvert
description: All-in-one unit conversion package. Supports time, length, mass, current, temperature, substance, intensity etc. Supports all units like metric, imperial, ancient, traditional etc.
version: 0.1.0-alpha.1

environment:
  sdk: ^3.1.0

dependencies:
  decimal: ^2.1.0
  rational: ^2.2.3
  slang: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  csv: ^5.0.1
  yaml: ^3.1.1
